#!/usr/bin/env python3
# -*- coding: utf-8 -*-


# Built-in modules
import os
import shutil
import subprocess
from functools import cached_property
from pathlib import Path

# Third-party modules
import pandas as pd
import plotly.graph_objects as go
import reflex as rx

# Internal modules
from oak_trade_agent.data.baci_dataset import baci
from oak_trade_agent.paths import get_output_dir


###############################################################################
class ReflexHeatmap:
    """
    Reflex app (Python-authored, React-generated web app):

    - Frontend is React/Next.js generated by Reflex
    - Backend is Python (state + event handlers)
    - Slider updates server-side state; UI re-renders with new Plotly figure

    Note: This module is meant to run under `reflex run` inside a Reflex project.
    """

    title = "Exporter → Importer heatmap (Top-N countries by total quantity)"

    @cached_property
    def df(self) -> pd.DataFrame:
        return baci.ranked_oak_df

    @cached_property
    def countries_ordered(self) -> list[str]:
        # Already sorted by rank (1 = largest)
        return baci.country_ranks.index.tolist()

    @cached_property
    def max_n(self) -> int:
        return len(self.countries_ordered)

    @cached_property
    def full_matrix(self) -> pd.DataFrame:
        """
        Plotly heatmap wants a dense 2D grid, so build the NxN matrix once and slice.
        """
        countries = self.countries_ordered
        sub = self.df[["exporter_name", "importer_name", "quantity"]]
        mat = sub.pivot_table(
            index="importer_name",
            columns="exporter_name",
            values="quantity",
            aggfunc="sum",
            fill_value=0.0,
        ).reindex(index=countries, columns=countries, fill_value=0.0)
        return mat

    def figure_for_n(self, n: int) -> go.Figure:
        countries = self.countries_ordered[:n]
        m = self.full_matrix.loc[countries, countries]

        fig = go.Figure(
            data=[
                go.Heatmap(
                    z=m.to_numpy(),
                    x=countries,
                    y=countries,
                    colorbar=dict(title="Quantity (tons)"),
                    hovertemplate=(
                        "Exporter: %{x}<br>"
                        "Importer: %{y}<br>"
                        "Quantity: %{z:,.3f}<extra></extra>"
                    ),
                )
            ]
        )
        fig.update_layout(
            title=self.title,
            width=900,
            height=900,
            margin=dict(l=120, r=80, t=60, b=120),
            xaxis=dict(title="Exporter country"),
            yaxis=dict(title="Importer country"),
        )
        return fig

    def __call__(self) -> None:
        app_dir = get_output_dir() / "reflex_app"
        app_dir.mkdir(parents=True, exist_ok=True)

        rxconfig_path = app_dir / "rxconfig.py"
        if not rxconfig_path.exists():
            if shutil.which("reflex") is None:
                raise RuntimeError(
                    "Reflex CLI not found. Install with: pip install reflex"
                )
            subprocess.run(
                ["reflex", "init", "--template", "blank", "--name", "reflex_app"],
                cwd=app_dir,
                input="\n",
                text=True,
                check=False,
            )
            if not rxconfig_path.exists():
                subprocess.run(
                    ["reflex", "init", "--template", "blank"],
                    cwd=app_dir,
                    input="\n",
                    text=True,
                    check=False,
                )
            if not rxconfig_path.exists():
                raise RuntimeError(
                    "Failed to initialize Reflex scaffold in output/reflex_app"
                )

        pkg_dir = app_dir / "reflex_app"
        pkg_dir.mkdir(exist_ok=True)

        shim_path = pkg_dir / "reflex_app.py"
        shim_path.write_text(
            "import reflex as rx\n"
            "from oak_trade_agent.dynamic.reflex_dynamic import app as oak_app\n\n"
            "app = oak_app\n"
        )

        init_path = pkg_dir / "__init__.py"
        if not init_path.exists():
            init_path.touch()

        env = os.environ.copy()
        repo_root = Path(__file__).resolve().parents[2]
        env["PYTHONPATH"] = str(repo_root) + (
            os.pathsep + env["PYTHONPATH"] if env.get("PYTHONPATH") else ""
        )
        subprocess.run(["reflex", "run"], cwd=app_dir, env=env, check=False)


###############################################################################
# Singleton (for sharing cached pivot across State instances)
reflex_heatmap = ReflexHeatmap()


###############################################################################
class HeatmapState(rx.State):
    """
    Reflex State:
    - Holds slider value
    - Exposes computed figure to the UI
    """

    top_n: int = 10

    @rx.var
    def max_n(self) -> int:
        return reflex_heatmap.max_n

    @rx.var
    def status(self) -> str:
        return f"Showing {int(self.top_n)} × {int(self.top_n)} countries"

    @rx.var
    def fig(self) -> dict:
        """
        Reflex components serialize Plotly figures as JSON-like dicts.
        """
        n = int(self.top_n)
        # Clamp defensively
        n = max(2, min(n, reflex_heatmap.max_n))
        return reflex_heatmap.figure_for_n(n).to_dict()

    def set_top_n(self, value) -> None:
        """Handle slider values (Radix slider sends a list/sequence)."""
        if isinstance(value, (list, tuple)) and value:
            value = value[0]
        self.top_n = int(value)


###############################################################################
def index() -> rx.Component:
    """
    Main page.
    """
    default_n = min(10, reflex_heatmap.max_n)

    return rx.container(
        rx.heading(reflex_heatmap.title, size="6"),
        rx.hstack(
            rx.text("Top N countries:"),
            rx.slider(
                min_=2,
                max_=HeatmapState.max_n,
                step=1,
                default_value=[default_n],
                on_change=HeatmapState.set_top_n,
                width="420px",
            ),
            rx.text(HeatmapState.status),
            spacing="4",
            align="center",
        ),
        rx.plotly(data=HeatmapState.fig),
        padding="24px",
        max_width="1100px",
    )


###############################################################################
# Reflex app object
app = rx.App()
app.add_page(index, route="/")

if __name__ == "__main__":
    reflex_heatmap()
